"""Technology skills dictionary and extraction utilities."""

import re

# Comprehensive technology skills organized by category
TECH_SKILLS: dict[str, list[str]] = {
    "programming_languages": [
        "python",
        "java",
        "java 8",
        "java 11",
        "java 17",
        "java 21",
        "javascript",
        "typescript",
        "c++",
        "c#",
        "c",
        "ruby",
        "go",
        "golang",
        "rust",
        "swift",
        "kotlin",
        "scala",
        "php",
        "perl",
        "r",
        "matlab",
        "dart",
        "lua",
        "haskell",
        "elixir",
        "clojure",
        "objective-c",
        "groovy",
        "shell",
        "bash",
        "powershell",
        "sql",
        "plsql",
        "vb.net",
        "visual basic",
        "cobol",
        "fortran",
        "assembly",
    ],
    "web_frameworks": [
        "react",
        "reactjs",
        "react.js",
        "angular",
        "angularjs",
        "vue",
        "vuejs",
        "vue.js",
        "svelte",
        "next.js",
        "nextjs",
        "nuxt",
        "nuxtjs",
        "gatsby",
        "django",
        "flask",
        "fastapi",
        "spring",
        "spring boot",
        "springboot",
        "spring cloud",
        "spring mvc",
        "spring security",
        "spring data",
        "hibernate",
        "jpa",
        "express",
        "expressjs",
        "nestjs",
        "rails",
        "ruby on rails",
        "asp.net",
        "asp.net core",
        "laravel",
        "symfony",
        "gin",
        "fiber",
        "blazor",
        "remix",
        "astro",
    ],
    "databases": [
        "mysql",
        "postgresql",
        "postgres",
        "mongodb",
        "redis",
        "elasticsearch",
        "sqlite",
        "oracle",
        "sql server",
        "mssql",
        "cassandra",
        "dynamodb",
        "couchdb",
        "neo4j",
        "mariadb",
        "cockroachdb",
        "firebase",
        "firestore",
        "supabase",
        "influxdb",
        "timescaledb",
        "memcached",
    ],
    "cloud_platforms": [
        "aws",
        "amazon web services",
        "azure",
        "microsoft azure",
        "gcp",
        "google cloud",
        "google cloud platform",
        "heroku",
        "digitalocean",
        "linode",
        "vercel",
        "netlify",
        "cloudflare",
        "alibaba cloud",
    ],
    "devops_tools": [
        "docker",
        "kubernetes",
        "k8s",
        "terraform",
        "ansible",
        "jenkins",
        "github actions",
        "gitlab ci",
        "circleci",
        "travis ci",
        "chef",
        "puppet",
        "vagrant",
        "helm",
        "argocd",
        "argo cd",
        "prometheus",
        "grafana",
        "datadog",
        "new relic",
        "splunk",
        "nginx",
        "apache",
        "caddy",
        "istio",
        "envoy",
    ],
    "data_science_ml": [
        "tensorflow",
        "pytorch",
        "keras",
        "scikit-learn",
        "sklearn",
        "pandas",
        "numpy",
        "scipy",
        "matplotlib",
        "seaborn",
        "jupyter",
        "spark",
        "pyspark",
        "hadoop",
        "hive",
        "airflow",
        "mlflow",
        "kubeflow",
        "sagemaker",
        "nltk",
        "spacy",
        "hugging face",
        "huggingface",
        "transformers",
        "opencv",
        "computer vision",
        "nlp",
        "natural language processing",
        "machine learning",
        "deep learning",
        "neural network",
        "random forest",
        "xgboost",
        "lightgbm",
        "catboost",
        "regression",
        "classification",
        "clustering",
        "generative ai",
        "llm",
        "large language model",
        "gpt",
        "bert",
    ],
    "mobile": [
        "react native",
        "flutter",
        "ionic",
        "xamarin",
        "swiftui",
        "android",
        "ios",
        "mobile development",
        "cordova",
        "capacitor",
    ],
    "version_control": [
        "git",
        "github",
        "gitlab",
        "bitbucket",
        "svn",
        "mercurial",
        "github copilot",
    ],
    "testing": [
        "junit",
        "pytest",
        "jest",
        "mocha",
        "chai",
        "cypress",
        "selenium",
        "playwright",
        "puppeteer",
        "testng",
        "rspec",
        "minitest",
        "unittest",
        "phpunit",
        "tdd",
        "bdd",
        "test driven development",
    ],
    "messaging_streaming": [
        "kafka",
        "rabbitmq",
        "activemq",
        "sqs",
        "sns",
        "pubsub",
        "celery",
        "sidekiq",
        "nats",
        "pulsar",
    ],
    "api_protocols": [
        "rest",
        "restful",
        "graphql",
        "grpc",
        "soap",
        "websocket",
        "openapi",
        "swagger",
        "postman",
    ],
    "security": [
        "oauth",
        "oauth2",
        "jwt",
        "saml",
        "ldap",
        "sso",
        "encryption",
        "ssl",
        "tls",
        "https",
        "owasp",
        "penetration testing",
        "vulnerability assessment",
    ],
    "other_tools": [
        "jira",
        "confluence",
        "slack",
        "trello",
        "figma",
        "sketch",
        "adobe xd",
        "webpack",
        "vite",
        "babel",
        "eslint",
        "prettier",
        "maven",
        "gradle",
        "npm",
        "yarn",
        "pnpm",
        "pip",
        "poetry",
        "linux",
        "unix",
        "windows server",
        "agile",
        "scrum",
        "kanban",
        "ci/cd",
        "cicd",
        "microservices",
        "serverless",
        "event driven",
        "design patterns",
        "sdlc",
        "solid",
        "oop",
        "functional programming",
        "data structures",
        "algorithms",
    ],
}

# Flatten all skills for quick lookup
ALL_SKILLS: set[str] = set()
for category_skills in TECH_SKILLS.values():
    ALL_SKILLS.update(category_skills)


def extract_skills(text: str) -> dict[str, list[str]]:
    """Extract technology skills from text, grouped by category.

    Returns a dict mapping category name to list of matched skills.
    """
    text_lower = text.lower()
    found: dict[str, list[str]] = {}

    for category, skills in TECH_SKILLS.items():
        matched = []
        for skill in skills:
            pattern = r"(?<![a-zA-Z])" + re.escape(skill) + r"(?![a-zA-Z])"
            if re.search(pattern, text_lower):
                matched.append(skill)
        if matched:
            found[category] = matched

    return found


def flatten_skills(categorized: dict[str, list[str]]) -> set[str]:
    """Flatten categorized skills into a single set."""
    result: set[str] = set()
    for skills in categorized.values():
        result.update(skills)
    return result
